# =============================================================================
# Create L1 Infrastructure (BNE)
# =============================================================================
# Creates a Blockchain Node Engine (BNE) node for L1 Ethereum access.
# BNE FULL nodes use public endpoints with API key authentication.
#
# WARNING: BNE nodes take several days to fully sync!
# This only needs to be run once per L1 network.
#
# After creation, you must:
# 1. Create an API key in GCP Console (APIs & Services → Credentials)
# 2. Note the l1_json_rpc_endpoint and l1_beacon_api_endpoint from output
# 3. Pass these values when running 'make provision'
#
# Usage:
#   gcloud builds submit . \
#     --config=cloudbuild/create-l1.yaml \
#     --substitutions=_NETWORK=base-mainnet
#
# =============================================================================

steps:
  # ---------------------------------------------------------------------------
  # Terraform Init
  # ---------------------------------------------------------------------------
  - id: 'terraform-init'
    name: 'hashicorp/terraform:1.9'
    dir: 'terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init \
          -backend-config="bucket=${_GCS_BUCKET}" \
          -backend-config="prefix=terraform/state/l1-${_NETWORK}"

  # ---------------------------------------------------------------------------
  # Terraform Apply (BNE)
  # ---------------------------------------------------------------------------
  - id: 'terraform-apply'
    name: 'hashicorp/terraform:1.9'
    dir: 'terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        set -e
        
        echo "=== Creating L1 Infrastructure (BNE) ==="
        echo "Network: ${_NETWORK}"
        echo ""
        echo "WARNING: BNE nodes take several days to sync!"
        echo ""
        
        terraform apply -auto-approve \
          -var="project_id=${_PROJECT_ID}" \
          -var="region=${_REGION}" \
          -var="zone=${_ZONE}" \
          -var="network=${_NETWORK}" \
          -var="create_l1=true" \
          -var="gcs_bucket=${_GCS_BUCKET}"
        
        echo ""
        echo "=== L1 Infrastructure Created ==="
        echo ""
        terraform output

  # ---------------------------------------------------------------------------
  # Show BNE Status and Endpoints
  # ---------------------------------------------------------------------------
  - id: 'show-status'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        
        echo "=== BNE Node Status ==="
        gcloud alpha blockchain-node-engine nodes describe "l1-${_L1_NETWORK}" \
          --location="${_REGION}" \
          --project="${_PROJECT_ID}" \
          --format="yaml(name,state,ethereumDetails.network,ethereumDetails.nodeType,connectionInfo.endpointInfo,ethereumDetails.additionalEndpoints)" \
          2>/dev/null || echo "Note: BNE CLI not available. Check console for status."
        
        echo ""
        echo "=== Public Endpoints ==="
        echo "JSON-RPC: $(gcloud alpha blockchain-node-engine nodes describe l1-${_L1_NETWORK} \
          --location=${_REGION} --project=${_PROJECT_ID} \
          --format='value(connectionInfo.endpointInfo.jsonRpcApiEndpoint)' 2>/dev/null || echo 'pending')"
        echo "Beacon:   $(gcloud alpha blockchain-node-engine nodes describe l1-${_L1_NETWORK} \
          --location=${_REGION} --project=${_PROJECT_ID} \
          --format='value(ethereumDetails.additionalEndpoints.beaconApiEndpoint)' 2>/dev/null || echo 'pending')"
        
        echo ""
        echo "=== Next Steps ==="
        echo "1. Wait for BNE to sync (check status in Cloud Console)"
        echo "2. Create an API key: GCP Console → APIs & Services → Credentials → Create API Key"
        echo "3. Build op-reth: make build RETH_BRANCH=main"
        echo "4. Provision VM:"
        echo "   make provision RETH_VERSION=<version> \\"
        echo "     SNAPSHOT_URL=<signed_url> \\"
        echo "     L1_RPC_ENDPOINT=https://<json-rpc-endpoint> \\"
        echo "     L1_BEACON_ENDPOINT=https://<beacon-endpoint> \\"
        echo "     L1_API_KEY=<your-api-key>"

substitutions:
  _PROJECT_ID: 'bct-prod-c3-tdx-3'
  _REGION: 'us-central1'
  _ZONE: 'us-central1-a'
  _NETWORK: 'base-mainnet'
  _GCS_BUCKET: 'base-mainnet-snapshot'
  # Derived from network (mainnet -> mainnet, sepolia -> holesky)
  _L1_NETWORK: 'mainnet'

options:
  logging: CLOUD_LOGGING_ONLY

tags: ['create-l1']

timeout: '7200s'  # 2 hours (BNE creation can take a while)
