# =============================================================================
# Terraform State Cleanup - Remove Orphaned Modules
# =============================================================================
# Usage:
#   gcloud builds submit . --config=cloudbuild/state-rm.yaml \
#     --substitutions=_MODULE="module.benchmark[\"vm-name\"]"
#
# This removes a module from Terraform state without destroying resources.
# Use this when resources have already been deleted manually.
# =============================================================================

substitutions:
  _GCS_BUCKET: "base-mainnet-snapshot"
  _MODULE: ""  # Required: module to remove, e.g., module.benchmark["vm-name"]

steps:
  # -------------------------------------------------------------------------
  # Step 1: Initialize Terraform with remote backend
  # -------------------------------------------------------------------------
  - id: "terraform-init"
    name: "hashicorp/terraform:1.9"
    dir: "terraform"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cat > backend.tf << 'EOF'
        terraform {
          backend "gcs" {
            bucket = "${_GCS_BUCKET}"
            prefix = "terraform/state/benchmark"
          }
        }
        EOF
        terraform init -input=false

  # -------------------------------------------------------------------------
  # Step 2: Remove module from state
  # -------------------------------------------------------------------------
  - id: "terraform-state-rm"
    name: "hashicorp/terraform:1.9"
    dir: "terraform"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Removing module from state: ${_MODULE}"
        terraform state rm '${_MODULE}' || echo "Module not found in state (may already be removed)"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "300s"
