# =============================================================================
# Cleanup Benchmark VMs (Terraform Destroy)
# =============================================================================
# Destroys benchmark instance(s). Can destroy single VM or all.
# Uses the new modular terraform structure at terraform/benchmark/
#
# Usage:
#   # Destroy single VM
#   gcloud builds submit . \
#     --config=cloudbuild/benchmark/cleanup.yaml \
#     --substitutions=_VM=op-reth-baseline
#
#   # Destroy all VMs
#   gcloud builds submit . \
#     --config=cloudbuild/benchmark/cleanup.yaml
#
# =============================================================================

steps:
  # ---------------------------------------------------------------------------
  # Parse config.toml and remove specified VM(s)
  # ---------------------------------------------------------------------------
  - id: 'parse-config'
    name: 'python:3.12-slim'
    entrypoint: 'python3'
    args:
      - '-c'
      - |
        import tomllib
        import json
        import sys

        # Load config.toml
        with open('config.toml', 'rb') as f:
            config = tomllib.load(f)

        # Get defaults for VM
        defaults = config.get('defaults', {}).get('vm', {})
        project = config.get('project', {})
        snapshot = config.get('snapshot', {})

        # Merge defaults into each VM
        vms = config.get('vm', [])
        for vm in vms:
            machine_type = vm.get('machine_type', defaults.get('machine_type', ''))
            is_lssd = machine_type.endswith('-lssd')
            for key, value in defaults.items():
                if key not in vm:
                    if is_lssd and key in ('storage_type', 'disk_size_gb'):
                        continue
                    vm[key] = value

        # Filter: if _VM is set, REMOVE that VM (keep others)
        # If _VM is empty, remove ALL VMs
        vm_filter = '${_VM}'
        if vm_filter:
            # Remove the specified VM, keep others
            original_count = len(vms)
            vms = [vm for vm in vms if vm.get('name') != vm_filter]
            if len(vms) == original_count:
                print(f"WARNING: VM '{vm_filter}' not found in config.toml", file=sys.stderr)
            print(f"Removing VM: {vm_filter}")
            print(f"Remaining VMs: {[vm.get('name') for vm in vms]}")
        else:
            # Remove all VMs
            print("Removing ALL VMs")
            vms = []

        # Write vms.json with remaining VMs (or empty list)
        vms_config = []
        for vm in vms:
            vms_config.append({
                'name': vm.get('name'),
                'zone': vm.get('zone', project.get('zone')),
                'machine_type': vm.get('machine_type'),
                'storage_type': vm.get('storage_type'),
                'disk_size_gb': vm.get('disk_size_gb', 15000),
                'provisioned_iops': vm.get('provisioned_iops'),
                'provisioned_throughput': vm.get('provisioned_throughput'),
                'confidential_compute': vm.get('confidential_compute', False),
            })
        
        with open('terraform/benchmark/vms.json', 'w') as f:
            json.dump(vms_config, f, indent=2)

        print(f"VMs to keep: {[vm['name'] for vm in vms_config]}")

        # Write config values
        with open('/workspace/project_id.txt', 'w') as f:
            f.write(project.get('project_id', ''))
        with open('/workspace/region.txt', 'w') as f:
            f.write(project.get('region', 'us-central1'))
        with open('/workspace/network.txt', 'w') as f:
            f.write(project.get('network', 'default'))
        with open('/workspace/snapshot_name.txt', 'w') as f:
            f.write(snapshot.get('name', ''))
        with open('/workspace/snapshot_disk_size_gb.txt', 'w') as f:
            f.write(str(snapshot.get('disk_size_gb', 12000)))
        with open('/workspace/reth_version.txt', 'w') as f:
            f.write(vms[0].get('reth_version', 'main') if vms else 'main')

  # ---------------------------------------------------------------------------
  # Terraform Init
  # ---------------------------------------------------------------------------
  - id: 'terraform-init'
    name: 'hashicorp/terraform:1.9'
    dir: 'terraform/benchmark'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init -input=false

  # ---------------------------------------------------------------------------
  # Terraform Apply (destroys removed instances)
  # ---------------------------------------------------------------------------
  - id: 'terraform-apply'
    name: 'hashicorp/terraform:1.9'
    dir: 'terraform/benchmark'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        set -e
        
        # Read config values
        PROJECT_ID=$$(cat /workspace/project_id.txt)
        REGION=$$(cat /workspace/region.txt)
        NETWORK=$$(cat /workspace/network.txt)
        SNAPSHOT_NAME=$$(cat /workspace/snapshot_name.txt)
        SNAPSHOT_DISK_SIZE_GB=$$(cat /workspace/snapshot_disk_size_gb.txt)
        RETH_VERSION=$$(cat /workspace/reth_version.txt)
        
        # Use default compute service account
        PROJECT_NUMBER=$$(gcloud projects describe $$PROJECT_ID --format="value(projectNumber)")
        SERVICE_ACCOUNT="$${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"
        
        echo "=== Applying Terraform (destroying removed instances) ==="
        terraform apply -auto-approve \
          -var="project_id=$$PROJECT_ID" \
          -var="region=$$REGION" \
          -var="network=$$NETWORK" \
          -var="snapshot_name=$$SNAPSHOT_NAME" \
          -var="snapshot_disk_size_gb=$$SNAPSHOT_DISK_SIZE_GB" \
          -var="reth_version=$$RETH_VERSION" \
          -var="service_account_email=$$SERVICE_ACCOUNT"
        
        echo ""
        echo "=== Remaining instances ==="
        terraform output -json vms || echo '{}'

  # ---------------------------------------------------------------------------
  # Upload updated state to GCS
  # ---------------------------------------------------------------------------
  - id: 'upload-to-gcs'
    name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        
        echo "=== Uploading updated files to GCS ==="
        
        # Upload vms.json
        gsutil cp terraform/benchmark/vms.json "gs://${_GCS_BUCKET}/terraform/vms.json"
        
        echo ""
        echo "=== Cleanup Complete ==="

substitutions:
  _GCS_BUCKET: 'base-mainnet-snapshot'
  _VM: ''  # Optional: specific VM to remove. If empty, removes all.

options:
  logging: CLOUD_LOGGING_ONLY

tags: ['cleanup', 'benchmark']

timeout: '600s'
